#!/usr/bin/env bash

set -u
set -e
set -o pipefail

declare TODO_FILE SERVER
SERVER="${TODO_SERVER:-vultr}"
TODO_FILE="${TODO_DIR}/todo.txt"

find "$TODO_FILE" | entr -n scp "${TODO_FILE}" "${SERVER}:.todo/todo.txt"
